#!/bin/bash

echo "🎬 GitLab 到 GitHub 迁移工具演示"
echo "================================="
echo ""

echo "步骤 1: 设置 GitLab Access Token"
echo "export GITLAB_ACCESS_TOKEN='glpat-your-gitlab-token-here'"
echo ""

echo "步骤 2: 运行设置检查"
echo "./setup.sh"
echo ""

echo "步骤 3: （可选）配置 GitHub Actions Importer 用于 CI 迁移"
echo "gh actions-importer configure"
echo "# 仅当需要迁移 CI/CD 时才执行"
echo ""

echo "步骤 4: 运行迁移脚本"
echo "python3 index.py"
echo ""
echo "可选：无本地克隆模式（使用 GitHub Import API）"
echo "export USE_GITHUB_IMPORT=1"
echo "python3 index.py"
echo ""

echo "📋 示例输出："
echo "🔍 正在获取 GitLab 仓库列表..."
echo "✅ 找到 15 个 GitLab 仓库"
echo ""
echo "📋 GitLab 仓库列表:"
echo "================================================================================"
echo " 1. my-awesome-project          🌐 公开   ✅ 有CI   ✨ 新建"
echo "    📝 一个很棒的项目"
echo "    📅 最后活动: 2025-08-20"
echo ""
echo " 2. private-tool               🔒 私有   ❌ 无CI   ✨ 新建"
echo "    📝 私有工具项目"
echo "    📅 最后活动: 2025-08-15"
echo ""
echo " 3. old-website                🌐 公开   ✅ 有CI   ⚠️  已存在"
echo "    📝 旧的网站项目"
echo "    📅 最后活动: 2024-12-01"
echo ""
echo "选择要迁移的仓库:"
echo "  输入数字选择单个仓库 (如: 1)"
echo "  输入范围选择多个仓库 (如: 1-3)"
echo "  输入多个数字用逗号分隔 (如: 1,2,5)"
echo "  输入 'all' 选择所有仓库"
echo "  输入 'q' 退出"
echo ""
echo "请选择: 1,2"
echo ""
echo "📋 将迁移以下 2 个仓库:"
echo "   - my-awesome-project (公开)"
echo "   - private-tool (私有)"
echo ""
echo "确认开始迁移? (y/N): y"
echo ""
echo "🚀 开始迁移 2 个仓库..."
echo "================================================================================"
echo ""
echo "[1/2] 处理仓库: my-awesome-project"
echo "📝 创建 GitHub 仓库: my-awesome-project"
echo "✅ GitHub 仓库创建成功: https://github.com/wuuashen/my-awesome-project"
echo "📦 迁移代码: my-awesome-project"
echo "  🔄 克隆 GitLab 仓库（包含所有分支）..."
echo "  🔗 添加 GitHub 远程仓库..."
echo "  🚀 推送所有分支和标签到 GitHub..."
echo "  ✅ my-awesome-project 代码迁移完成"
echo "  🔧 迁移 CI/CD 配置: my-awesome-project"
echo "  ✅ my-awesome-project CI/CD 迁移完成"
echo ""
echo "[2/2] 处理仓库: private-tool"
echo "📝 创建 GitHub 仓库: private-tool"
echo "✅ GitHub 仓库创建成功: https://github.com/wuuashen/private-tool"
echo "📦 迁移代码: private-tool"
echo "  🔄 克隆 GitLab 仓库（包含所有分支）..."
echo "  🔗 添加 GitHub 远程仓库..."
echo "  🚀 推送所有分支和标签到 GitHub..."
echo "  ✅ private-tool 代码迁移完成"
echo "  ℹ️  private-tool 无 CI 配置，跳过"
echo ""
echo "================================================================================"
echo "🎉 迁移完成!"
echo "📊 统计:"
echo "   代码迁移成功: 2/2"
echo "   CI/CD迁移成功: 1"
echo "   输出目录: ./migration-output"
echo ""
echo "✨ 新建的 GitHub 仓库:"
echo "   https://github.com/wuuashen/my-awesome-project"
echo "   https://github.com/wuuashen/private-tool"
echo ""

echo "🚀 现在您就可以使用真实的 token 运行迁移了！"
